/*
 * Copyright (c) 2016, Liberty Mutual
 * Proprietary and Confidential
 * All Rights Reserved
 */
package com.lmig.uscm.cl.predictivemodel.enums;
/**
 * @author Abhi Verma
 * 
 */
public enum CoeffInput 
{
    EMSREQUIREDIND,
    LM_DEBRISPRESENTIND,
    LM_BOARDUPREQUIREDIND,
    LM_FLOORDAMAGETYPE,
    LM_FLOOROFORIGINTYPE,
    LM_FLOORSDAMAGEDIND,
    LM_ISHOMEHABITABLEIND,
    LM_NUMBERROOMSFLOORDAMAGETYPE,
    LM_NUMBERROOMSIMPACTEDTYPE,
    LM_POWERTOHOMEIND,
    LM_SIDINGDAMAGEDIND,
    LOSSCATEGORYTYPE,
    LOSSCAUSETYPE,
    POLICY_UDRWRTNG_PGM_DESC,
    REPORTEDBYTYPE,
    LM_ROOFDAMAGEDIND,
    APST,
    PPUN,
    BLDG,
    MLD1,
    MLD2,
    RGN1,
    RGN2,
    RGN3,
    RGN4,
    RGN5,
    SEASON0,
    SEASON1,
    SEASON2,
    SEASON3,
    DEDUCTIBLE,
    SEASON,
    INCIDENTLIMITG,
    REGION,
    LM_KITCHENUSABLEIND,
    LM_PP_JEWELRYIND,
    LM_SMOKEDAMAGEIND,
    TIME,
    LM_NUMBEROFELEVATIONSTYPE,
    LM_ROOFMATERIALTYPE,
    REPORTLAG,
    LM_CABINETSDAMAGEDIND,
    NMBRROOMSIMPCT_FLOORSDMGIND,
    LOSSCATEGORYTYPE_EMSREQUIRED,
    
    //APDSubro Inputs
    SEVERITY,
    RENTALIND,
    TOTALLOSSIND,
    INITIALPOINTIMPACT,
    //LOSSCAUSETYPE, repeat
    MULTICARIND,
    VEHICLEMAKE,
    VEHICLEYEAR,
    DEDUCTIBLEWAIVED,
    JURISDICTION,
    DEDUCTIBLETODATE,
    COVERAGEDEDUCTIBLE,
    GROSSLOSS,
    DRIVERAGE,
    CLAIMTIER,
    HITANDRUN
}